### ISSUE TITLE
TaskBuilder update breaks my tasks

### ISSUE THREAD

**Issue by forki** [rspeele/TaskBuilder.fs#15]
-    TaskBuilder.fs (1.0.1)
+   TaskBuilder.fs (1.1)

![image](https://user-images.githubusercontent.com/57396/36377465-8c397850-1577-11e8-9299-630b79da32e4.png)

any ideas? It breaks everything for me

**Comment by gusty** [comment]
Is this after applying my PR https://github.com/rspeele/TaskBuilder.fs/pull/14 ?

**Comment by forki** [comment]
That's not merged yet, right? So I assume no. This is with the official
nuget package.

Am 19.02.2018 13:40 schrieb "Gustavo Leon" <notifications@github.com>:

**Comment by gusty** [comment]
Ah ok, since you posted in the other issue I though it was related to my fix.
Anyway I can have a look, can you manage to get a minimal repro? If I find a solution we can add it as a test.

**Comment by forki** [comment]
I posted it there because I hoped to get wider attention to the issue.

Will try to reduce it

Am 19.02.2018 13:43 schrieb "Gustavo Leon" <notifications@github.com>:

**Comment by forki** [comment]
let t = task { return Some "x" }

    let getX  = task {
        let! r = t
        if r = None then
            return! failwithf "Could not find x" 
        else
            return r
    }

**Comment by gusty** [comment]
I found a way to solve it in my PR but good luck with the original code ;)

If you want I can include another commit with this test and its fix.

**Comment by forki** [comment]
yes please. it's a regression and hurts us badly.

**Comment by rspeele** [comment]
I will be checking out Gustavo's PR this week to get F# 4.0 compat back. Sounds like it should be possible to fix with that code.

In the meantime here is a quick fix for this regression applied to the existing codebase:

https://www.nuget.org/packages/TaskBuilder.fs/1.1.1

Just out of curiosity, is there any reason you use `return!` instead of `return` here?

**Comment by forki** [comment]
Yes the reason is @dsyme teached me that this is the correct way to do it

Am 19.02.2018 16:45 schrieb "Robert Peele" <notifications@github.com>:

I will be checking out Gustavo's PR this week to get F# 4.0 compat back.
Sounds like it should be possible to fix with that code.

In the meantime here is a quick fix for this regression applied to the
existing codebase:

https://www.nuget.org/packages/TaskBuilder.fs/1.1.1

Just out of curiosity, is there any reason you use return! instead of return
here?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rspeele/TaskBuilder.fs/issues/15#issuecomment-366730598>,
or mute the thread

**Comment by gusty** [comment]
I also think ``return`` makes more sense and am curious to hear @dsyme explanations.

Anyway I updated my PR with the fix. If you can pull it and test your code please let me know.

**Comment by forki** [comment]
I think it's value vs. continuation or something.

Am 19.02.2018 20:02 schrieb "Gustavo Leon" <notifications@github.com>:

**Comment by dsyme** [comment]
> Just out of curiosity, is there any reason you use return! instead of return here?

You can do either - either way the failwith will fail to return either "return" type ``unit`` or ``Task<unit>`` or whatever.

**Comment by forki** [comment]
Good. Thanks for clarification!

Am 20.02.2018 19:25 schrieb "Don Syme" <notifications@github.com>:

**Comment by rspeele** [comment]
Just FYI, [1.2.0 rc](https://www.nuget.org/packages/TaskBuilder.fs/1.2.0-rc) is available now.
This has Gustavo's changes for 4.0 compability. It _should_ behave the same way both in terms of type inference and runtime performance, and seems to from my testing, but I don't have a big codebase to check against.

@forki would you be willing to try it out and see how it works with your code?

**Comment by forki** [comment]
The module/namespace 'FSharp.Control.Tasks.TaskBuilder' from compilation unit 'TaskBuilder.fs' did not contain the namespace, module or type 'ContextInsensitiveTaskBuilder'

**Comment by forki** [comment]
so basically whole projet breaks again. what do I need to do? and can you please write that into release notes

**Comment by gusty** [comment]
Yes, this is a minor issue, easy to fix, there were some refactoring in the namespaces/modules.

Looking at the code the way it is right now you won't find ``ContextInsensitiveTaskBuilder`` anywhere, you will find that builder like this:

    FSharp.Control.Tasks.ContextInsensitive.TaskBuilder

Now, there are 2 ways to fix it, either you fix your code, or we can have a look at the taksbuilder and see if we can fix the taskbuilder code.

But I wonder why are you referencing that builder class? The only thing you need to reference is the builder instance: 

    FSharp.Control.Tasks.ContextInsensitive.task

or ideally:

    open FSharp.Control.Tasks.ContextInsensitive

    let x = task { ...

**Comment by rspeele** [comment]
In the RC, there is no longer a separate class for `ContextInsensitiveTaskBuilder`. There's just one `TaskBuilder` type and different extension methods on that type depending which module you open.

In what context are you referring to the task builder type by name? You could "fix" it by referring to `FSharp.Control.Tasks.TaskBuilder.TaskBuilder` but right now that isn't a great option as that module is marked obsolete (just to hide it from intellisense while still being able to use it from inline code). We might have to refactor and add type aliases to keep code that referred to the type name `ContextInsensitiveTaskBuilder` working.

**Comment by forki** [comment]
I'm lost. What namespace do I need to open to get old behavior?

**Comment by gusty** [comment]
@forki. See the last snippet in my previous comment.

**Comment by forki** [comment]
![image](https://user-images.githubusercontent.com/57396/36665064-d1421b40-1ae6-11e8-945d-deae374dbf2b.png)

I still get that error everywhere. Is it related to giraffe? Do they need to update first?

**Comment by gusty** [comment]
I'm not sure if this is your case but if you are using TaskBuilder.fs in your project and at the same time your project uses another project that uses TaskBuilder (like Giraffe) you might run into problems, since the namespaces are the same.

I think ideally libraries using TaskBuilder shouldn't re-export TaskBuilder to avoid this.

**Comment by dustinmoris** [comment]
@gusty Could you elaborate what you mean? How can I not expose the task CE after referencing TaskBuilder.fs?

**Comment by gusty** [comment]
Honestly I don't know, I just said "ideally", but I know that in some scenarios this is problematic, it happened to me with other libraries.

To answer your question I need to know more details, specifically how it is included in Giraffe, I haven't look at it.

But if you are copying the code, you can simply change the namespaces or mark it as internal, this will allow the users of Giraffe to use their own taskbuilders at possible different versions.

In the readme it states:

> This is public domain code. I encourage you to simply copy TaskBuilder.fs into your own project and use it as you see fit. It is not necessary to credit me or include any legal notice with your copy of the code.

I guess it's also fine to change the namespaces, but I know it's not an elegant solution.

**Comment by ForNeVeR** [comment]
I think newer versions of Giraffe use TaskBuilder from NuGet, right?

https://github.com/giraffe-fsharp/Giraffe/blob/4b5852e80e49c11e11bb66a4065afd79b6ad778b/src/Giraffe/Giraffe.fsproj#L35

**Comment by forki** [comment]
Yes. Including it via copy of the file worked excellent, but now we have a
bit of a stability issue. I hope we get that worked out soon.
I think the best way forward is for Giraffe to push a prerelease that is
compiled against beta TaskBuilder.fs. I could then paket update all of it
in my production apps and verify that everything plays well together.

And then we do a coordinated release of TaskBuilder.fs and giraffe so that
others do experience that issue.

Am 27.02.2018 04:56 schrieb "Friedrich von Never" <notifications@github.com

**Comment by forki** [comment]
@rspeele not sure why you closed it, but I can now confirm that a simultaneous update of taskbuilder and giraffe indeed works. so can you and @dustinmoris please somehow sync?

**Comment by dustinmoris** [comment]
Hi, just to reiterate everything:

- In theory there were breaking changes between TaskBuilder.fs 1.0.1 and the versions after (1.1 and now 1.2-rc).
- Giraffe has a dependency on the the TaskBuilder.fs NuGet package.
- Updating Giraffe to the latest 1.2-rc build of TaskBuilder.fs fixes the errors for @forki because there is no conflict between the old and the new namespaces of TaskBuilder.fs.
- However, a project which references Giraffe doesn't require an explicit reference to TaskBuilder.fs anymore, unless it wants to use a higher version and do some assembly redirects.

As @forki suggested if we coordinate the release of TaskBuilder.fs and Giraffe in the future then such breaking conflicts can be avoided for end users, but I also believe that perhaps it would have been better to version TaskBuilder.fs accordingly to the breaking changes (e.g. from 1.x.x to 2.x.x) and then it would have been more obvious (and expected) that an additional reference to a higher major version of TaskBuilder.fs might have caused issues with Giraffe if Giraffe hasn't been updated yet.

Am I missing something?

So my final question is what is the ETA for TaskBuilder.fs 1.2 stable?

**Comment by rspeele** [comment]
I opened a new issue for planning the release. #18
