### ISSUE TITLE
The type 'Threading.Tasks.Task' is not compatible with the type 'Threading.Tasks.Task<'a>'

### ISSUE THREAD

**Issue by dustinmoris** [rspeele/TaskBuilder.fs#23]
I am not sure if I am doing something wrong or if this is a bug, but I am getting the following error when trying to do a `do!` binding:

```
The type 'Threading.Tasks.Task' is not compatible with the type 'Threading.Tasks.Task<'a>'
```

![image](https://user-images.githubusercontent.com/4580714/44323614-8fafd300-a44a-11e8-9910-27ec0d0876af.png)

This is a netcoreapp2.1 project, with the latest TaskBuilder.fs and built on the latest 2.1.400 SDK.

I also opened `open FSharp.Control.Tasks.V2.ContextInsensitive`.

Did I miss something?

**Comment by forki** [comment]
Are you sure the error is not in next line? Different result type than inside the try/catch that happened to me a lot and error is always reported to early

**Comment by dustinmoris** [comment]
Yeah I'm pretty sure, because the compiler throws the error on this line
too and the same code doesn't have a type problem with the TaskBuilder
which has the unitTask.

**Comment by forki** [comment]
Ok. Was just one thing that I was seeing a lot...

**Comment by gusty** [comment]
Can you provide small repro?

**Comment by dustinmoris** [comment]
Ok, I found the issue. It was between my chair and my keyboard. Thanks for the help!

**Comment by forki** [comment]
Could you please be more specific? I think we still have at least a error
reporting issue here - probably inside of the F# compiler itself. (at least
that's what I was referring to in the stuff I was seeing)

Dustin Moris Gorski <notifications@github.com> schrieb am Mo., 20. Aug.
2018, 21:09:

**Comment by dustinmoris** [comment]
@forki In my case I missed one place where I didn't change from `FSharp.Control.Tasks` to `FSharp.Control.Tasks.V2`.
