### ISSUE TITLE
Non-generic Tasks

### ISSUE THREAD

**Issue by kentcb** [rspeele/TaskBuilder.fs#36]
Hello,

Thanks for this useful library.

What is the guidance for working with non-generic `Task`s? A simple repro of my issue:

```F#
let doesThisWork : System.Threading.Tasks.Task =
    task {
        do! System.Threading.Tasks.Task.Delay(1000)
    }
```

Which produces this error:

```F#
FS0001    This expression was expected to have type
    'Threading.Tasks.Task'    
but here has type
    'Threading.Tasks.Task<unit>'
```

One workaround we have is:

```F#
type System.Threading.Tasks.Task with

    static member Ignore (task: Task<'T>) : Task =
        task :> Task
```

And then:

```F#
let doesThisWork : System.Threading.Tasks.Task =
    task {
        do! System.Threading.Tasks.Task.Delay(1000)
    } |> Task.Ignore
```

But this feels rather hacky.

**Comment by gusty** [comment]
It doesn't feel hacky to me.
It feels explicit.

**Comment by dsyme** [comment]
Yes it feels pretty reasonable to me

**Comment by isaacabraham** [comment]
@kentcb This is pretty standard with generics when going from F# unit (as 'T) to void in C# where you have this "equivalent" type for the void case in C# but just a single type in F#.

**Comment by gusty** [comment]
Actually, F#+ has exactly that same `Task.Ignore` function, for the same purpose.

**Comment by rspeele** [comment]
Another option is the `upcast` operator. I find this nice when implementing interfaces that want a non-generic `Task`.

```
let doesThisWork : System.Threading.Tasks.Task =
    upcast task {
        do! System.Threading.Tasks.Task.Delay(1000)
    }
```

**Comment by kentcb** [comment]
Thanks all! Glad we're on the right track.
