### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by dustinmoris** [rspeele/TaskBuilder.fs#4]
Hi, first of all thanks for building this fancy task builder! From my first few tests it works like a charm! I came across it, because someone used your TaskBuilder.fs to improve the performance of the [Giraffe](https://github.com/dustinmoris/Giraffe) web framework and therefore I would be interested in consuming it via a NuGet package rather than having to copy/paste it every time you improve it or bug fix something. It would also make it easier by having it as a well documented dependency and avoid other contributors to try and change the TaskBuilder.fs in Giraffe when really they should probably discuss any changes/improvements with you here first so that everyone can benefit from it.

Would you be interested in making your TaskBuilder.fs accessible via a NuGet library? If yes I can even help out with a PR myself. Let me know and thank you for open sourcing it!

**Comment by rspeele** [comment]
I'm in favor of it in principle. I don't know whether it should be a package including the source file or a compiled .dll, but I guess people can always grab the source themselves if they prefer to do it that way...

Anyway, feel free to open a PR!

**Comment by NinoFloris** [comment]
If this happens you might also want to add/change the Obsolete attribute on the TaskBuilder to just use `EditorBrowsable(EditorBrowsableState.Never)` as it's in a different assembly that should work.
