### ISSUE TITLE
BenchmarkDotNet results

### ISSUE THREAD

**Issue by NinoFloris** [rspeele/TaskBuilder.fs#6]
Alright locally moved the benchmark suite to BDN and these are the results
![screen shot 2017-08-18 at 18 10 11](https://user-images.githubusercontent.com/4218809/29467370-903e5b32-8440-11e7-9c02-10211f7b17e9.png)

TaskBuilder is looking good, expected to have a bit more allocs but overall the mean times are very close to C#.

Would you be willing to pull the changes of the setup for BDN and new proj system? Then I'll open a PR :)

**Comment by rspeele** [comment]
Sure, sounds good. Glad to see the benchmark results look decent.

**Comment by rspeele** [comment]
Closing this issue as a non-issue. Still willing to accept a PR of course.
